### ISSUE TITLE
what about background blurring?

### ISSUE THREAD

**Issue by channchetra** [peterflynn/xd-copy-css-code#1]
That's good way and just waiting for long about this function but still can't copy blurring background of an obj 😢

**Comment by peterflynn** [comment]
Browsers don't have very good support for background blur effects -- only Webkit/Safari currently supports `background-filter`, and only with a `--webkit-` prefix.  But in v1.1 I've added support for emitting this CSS, along with a warning note about browser compatibility.

Let me know if there are any improvements to the generated CSS for this that you'd suggest.
